---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sak-cni
rules:
  - apiGroups: ["k8s.cni.cncf.io"]
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/status
    verbs:
      - get
      - update
  - apiGroups:
      - ""
      - events.k8s.io
    resources:
      - events
    verbs:
      - create
      - patch
      - update
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sak-cni
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sak-cni
subjects:
- kind: ServiceAccount
  name: sak-cni
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sak-cni
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-sak-cni-ds
  namespace: kube-system
  labels:
    tier: node
    app: sak-cni
    name: sak-cni
spec:
  selector:
    matchLabels:
      name: sak-cni
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        tier: node
        app: sak-cni
        name: sak-cni
    spec:
      hostNetwork: true
      tolerations:
      - operator: Exists
        effect: NoSchedule
      - operator: Exists
        effect: NoExecute
      serviceAccountName: sak-cni
      containers:
      - name: kube-sak-cni
        image: docker.io/dougbtv/sak-cni:latest
        imagePullPolicy: Always
        command: ["/entrypoint.sh"]
        args:
        - "--sak-cni-conf-file=auto"
        - "--cni-version=0.3.1"
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
        securityContext:
          privileged: true
        volumeMounts:
        - name: cni
          mountPath: /host/etc/cni/net.d
        - name: cnibin
          mountPath: /host/opt/cni/bin
      initContainers:
        - name: install-sak-cni-binary
          image: docker.io/dougbtv/sak-cni:latest
          command:
            - "cp"
            - "/usr/src/sak-cni/bin/swiss-army-knife"
            - "/host/opt/cni/bin/swiss-army-knife"
          resources:
            requests:
              cpu: "10m"
              memory: "15Mi"
          securityContext:
            privileged: true
          volumeMounts:
            - name: cnibin
              mountPath: /host/opt/cni/bin
              mountPropagation: Bidirectional
      terminationGracePeriodSeconds: 10
      volumes:
        - name: cni
          hostPath:
            path: /etc/cni/net.d
        - name: cnibin
          hostPath:
            path: /opt/cni/bin